---
collections:
  - name: community.general
    version: 10.2.0
  - name: community.sops
    version: 2.0.0
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 5.1.2
  - name: kubernetes.core
    version: 5.0.0
  - name: devsec.hardening
    version: 10.2.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.4
  - name: githubixx.ansible_role_wireguard
    src: https://github.com/githubixx/ansible-role-wireguard.git
    version: 17.1.0
  - name: artis3n.tailscale
    src: https://github.com/artis3n/ansible-role-tailscale.git
    version: 4.5.0
