---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider:
      name: cloudflare
    env:
      - name: &name CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: &secret cloudflare-api-secret #XXX: fix secret feed
            key: *name
      - name: &name CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: *secret
            key: *name
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      # - --cloudflare-proxied
      - --events
      - --ignore-ingress-tls-spec
      - --ingress-class=external
      - --default-targets=cluster.kaminek.me
    policy: sync
    sources: ["crd", "ingress"]
    txtOwnerId: default
    txtPrefix: homelab.k8s.
    domainFilters: ["kaminek.me"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
